server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  application:
    name: student-selection-course
  config:
    import:
      - application-web.yml
      - application-log.yml
      - application-datasource.yml
      - application-mybatisPlus.yml
      - application-redis.yml